### ISSUE TITLE
Can not install stable 3 on 10.9.11 FreeBSD (The checksum of the received data doesn't match.)

### ISSUE THREAD

**Issue by make-nz** [jellyfin/jellyfin-plugin-dlna#101] opened 2024-11-08 15:46 UTC
Can not install stable 3 on 10.9.11 FreeBSD 
![Image](https://github.com/user-attachments/assets/9bab5006-60f1-4dd2-8142-5efb3cf97abb)

![Image](https://github.com/user-attachments/assets/205c36a1-bc43-4d8d-8721-3a88c55793ea)

**Comment by disgustipated** [comment] 2024-11-08 16:22
It looks like youve posted a couple different issues regarding interacting with the plugin, have you reviewed the logs for information that might help find whats going on? if youre not sure what the logs mean youll have to attach them as well for anyone to help. without looking at anything im guessing permissions issues but youll have to upload your logs if you cant find anything from them.

**Comment by make-nz** [comment] 2024-11-08 16:29
Permissions… No  v2 can be installed without problems:
![Image](https://github.com/user-attachments/assets/f6cfc82a-b138-4215-9d80-b6bde8be8d54)

**Comment by disgustipated** [comment] 2024-11-08 16:31
Youll have to evaluate your logs. and if you need help with that youll have to attach them.

**Comment by make-nz** [comment] 2024-11-08 16:33
Been trying to find something in the logs, but they are very long.
Which logs, would you like to have?

**Comment by make-nz** [comment] 2024-11-08 17:14
This worked:
> [2024-11-08 16:48:40.001 +01:00] [INF] [24] Emby.Server.Implementations.Updates.InstallationManager: Plugin "installed": "DLNA" "2.0.0.0"
[2024-11-08 16:48:40.019 +01:00] [INF] [24] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.

and here is an checksum issue:

> [2024-11-08 16:51:37.459 +01:00] [ERR] [100] Emby.Server.Implementations.Updates.InstallationManager: **The checksums didn't match while installing "DLNA", expected: "10e6c4dab3c5b0bb42d434dfef974ebc", got: "2B88FB8B370650F1CEDCA0A3A6D4A050"**
[2024-11-08 16:51:37.459 +01:00] [ERR] [100] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[2024-11-08 16:51:37.676 +01:00] [ERR] [100] Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask: Error updating "DLNA"
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
[2024-11-08 16:51:37.677 +01:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 2 seconds

**Comment by disgustipated** [comment] 2024-11-08 17:21
You have some file system access issues with the system.IO calls. I'd question the performance of whatever filesystem you have JF server running on with the line ``` Reading the request body timed out due to data arriving too slowly. ``` it looks like you have quite a few other issues outside of just using this plugin.

**Comment by make-nz** [comment] 2024-11-08 17:49
The server did some large scans during this time, but is by no means working hard at all in general.
This server has been running jellyfin for many years.

**And this must bee an issue:**
The checksums didn't match while installing "DLNA", expected: "10e6c4dab3c5b0bb42d434dfef974ebc", got: "2B88FB8B370650F1CEDCA0A3A6D4A050"

**Comment by disgustipated** [comment] 2024-11-08 17:52
if you cant use the uninstall option you should be able to remove the DLNA_#.#.#.# folders and then reinstall

**Comment by make-nz** [comment] 2024-11-08 18:38
Yes, I do restarts after removing a plugin manually. And again after putting  a new plugin in the plugins folder.

Thanks, I did not see the 10.10 requirement for v4/5

But this for v3 on 10.9.11 ( cat log_20241108.log | grep -A 2 "The checksums didn't match while installing" )

> [2024-11-08 16:38:21.574 +01:00] [ERR] [53] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing "DLNA", expected: "10e6c4dab3c5b0bb42d434dfef974ebc", got: "2B88FB8B370650F1CEDCA0A3A6D4A050"
[2024-11-08 16:38:21.574 +01:00] [ERR] [53] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
--
[2024-11-08 16:43:26.181 +01:00] [ERR] [54] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing "DLNA", expected: "10e6c4dab3c5b0bb42d434dfef974ebc", got: "2B88FB8B370650F1CEDCA0A3A6D4A050"
[2024-11-08 16:43:26.181 +01:00] [ERR] [54] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
--
[2024-11-08 16:48:17.992 +01:00] [ERR] [61] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing "DLNA", expected: "10e6c4dab3c5b0bb42d434dfef974ebc", got: "2B88FB8B370650F1CEDCA0A3A6D4A050"
[2024-11-08 16:48:17.993 +01:00] [ERR] [61] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
--
[2024-11-08 16:51:37.459 +01:00] [ERR] [100] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing "DLNA", expected: "10e6c4dab3c5b0bb42d434dfef974ebc", got: "2B88FB8B370650F1CEDCA0A3A6D4A050"
[2024-11-08 16:51:37.459 +01:00] [ERR] [100] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.

**Comment by make-nz** [comment] 2024-11-08 21:15
Did some more testing:

> root@jellyfin:~ # curl -sL http://repo.jellyfin.org/releases/plugin/dlna/dlna_3.0.0.0.zip | md5
2b88fb8b370650f1cedca0a3a6d4a050
root@jellyfin:~ # curl -sL http://repo.jellyfin.org/releases/plugin/dlna/dlna_2.0.0.0.zip | md5
2d5352445ed378318fee7aec39e12d15

they match with the ones from https://repo.jellyfin.org/?path=/plugin/dlna
`dlna_3.0.0.0.zip 		2b88fb8b370650f1cedca0a3a6d4a050 	163.43K 	Mon, 02 Sep 2024 17:22:27 +0000`
`dlna_2.0.0.0.zip 		2d5352445ed378318fee7aec39e12d15 	163.41K 	Sun, 26 May 2024 20:40:49 +0000`

**Comment by disgustipated** [comment] 2024-11-08 21:47
Confirmed I got the same too with v3 on 10.10.1. I recall there was something odd with the catalog push with the version 3, you could try this build artifact manually
https://github.com/jellyfin/jellyfin-plugin-dlna/actions/runs/11473845690

**Comment by Bond-009** [comment] 2024-11-10 09:42
Can you try again? It should be fixed now.

**Comment by disgustipated** [comment] 2024-11-10 11:43
Looks good!

**Closed** 2024-11-10 14:44 UTC
